/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_org_cardboardbox_wonderdroid_WonderSwan_Header */

#ifndef _Included_uk_org_cardboardbox_wonderdroid_WonderSwan_Header
#define _Included_uk_org_cardboardbox_wonderdroid_WonderSwan_Header
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
